### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by ruzaq** [brmlab/brmsklad#1]
brmsklad seems to be not working on PHP7 (Ubuntu 16.04). Currently it is a show stopper for possible ongoing OS upgrade.

PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/brmsklad/lib/Cake/Utility/String.php on line 26

"./Console/cake upgrade all" didnt help.

**Comment by smarek** [comment]
Should  be fixed by 235a541597eadd1e8096ccf1c1683ef8240eacd3
Test please

**Comment by ruzaq** [comment]
It works. Thanks
